// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (user_id, name, account_type, balance, currency)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, account_type, balance, currency, is_active, created_at, updated_at, deleted_at
`

type CreateAccountParams struct {
	UserID      int64
	Name        string
	AccountType string
	Balance     pgtype.Numeric
	Currency    string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.UserID,
		arg.Name,
		arg.AccountType,
		arg.Balance,
		arg.Currency,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AccountType,
		&i.Balance,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAccountByIDForUser = `-- name: GetAccountByIDForUser :one
SELECT id, user_id, name, account_type, balance, currency, is_active, created_at, updated_at, deleted_at
FROM accounts
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
`

type GetAccountByIDForUserParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetAccountByIDForUser(ctx context.Context, arg GetAccountByIDForUserParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByIDForUser, arg.ID, arg.UserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AccountType,
		&i.Balance,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAccountByIDForUserForUpdate = `-- name: GetAccountByIDForUserForUpdate :one
SELECT id, user_id, name, account_type, balance, currency, is_active, created_at, updated_at, deleted_at
FROM accounts
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
FOR UPDATE
`

type GetAccountByIDForUserForUpdateParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetAccountByIDForUserForUpdate(ctx context.Context, arg GetAccountByIDForUserForUpdateParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByIDForUserForUpdate, arg.ID, arg.UserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AccountType,
		&i.Balance,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAccountsByUser = `-- name: ListAccountsByUser :many
SELECT id, user_id, name, account_type, balance, currency, is_active, created_at, updated_at, deleted_at
FROM accounts
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAccountsByUser(ctx context.Context, userID int64) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.AccountType,
			&i.Balance,
			&i.Currency,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAccountByIDForUser = `-- name: SoftDeleteAccountByIDForUser :execrows
UPDATE accounts
SET deleted_at = NOW(),
    is_active = FALSE,
    updated_at = NOW()
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteAccountByIDForUserParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) SoftDeleteAccountByIDForUser(ctx context.Context, arg SoftDeleteAccountByIDForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAccountByIDForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAccountByIDForUser = `-- name: UpdateAccountByIDForUser :one
UPDATE accounts
SET name = COALESCE($3::text, name),
    account_type = COALESCE($4::text, account_type),
    currency = COALESCE($5::text, currency),
    updated_at = NOW()
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
RETURNING id, user_id, name, account_type, balance, currency, is_active, created_at, updated_at, deleted_at
`

type UpdateAccountByIDForUserParams struct {
	ID          int64
	UserID      int64
	Name        pgtype.Text
	AccountType pgtype.Text
	Currency    pgtype.Text
}

func (q *Queries) UpdateAccountByIDForUser(ctx context.Context, arg UpdateAccountByIDForUserParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountByIDForUser,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.AccountType,
		arg.Currency,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AccountType,
		&i.Balance,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
