// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const categoryAccessibleForUser = `-- name: CategoryAccessibleForUser :one
SELECT id
FROM categories
WHERE id = $1
  AND (user_id = $2 OR is_system = TRUE)
LIMIT 1
`

type CategoryAccessibleForUserParams struct {
	ID     int64
	UserID pgtype.Int8
}

func (q *Queries) CategoryAccessibleForUser(ctx context.Context, arg CategoryAccessibleForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, categoryAccessibleForUser, arg.ID, arg.UserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    account_id, category_id, amount, currency, type, description, notes, transacted_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, account_id, category_id, recurring_id, amount, currency, type, description, notes, transacted_at, created_at, updated_at, deleted_at
`

type CreateTransactionParams struct {
	AccountID    int64
	CategoryID   pgtype.Int8
	Amount       pgtype.Numeric
	Currency     string
	Type         string
	Description  string
	Notes        pgtype.Text
	TransactedAt pgtype.Date
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.AccountID,
		arg.CategoryID,
		arg.Amount,
		arg.Currency,
		arg.Type,
		arg.Description,
		arg.Notes,
		arg.TransactedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CategoryID,
		&i.RecurringID,
		&i.Amount,
		&i.Currency,
		&i.Type,
		&i.Description,
		&i.Notes,
		&i.TransactedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTransactionByIDForUser = `-- name: GetTransactionByIDForUser :one
SELECT t.id, t.account_id, t.category_id, t.recurring_id, t.amount, t.currency, t.type, t.description, t.notes, t.transacted_at, t.created_at, t.updated_at, t.deleted_at
FROM transactions t
JOIN accounts a ON a.id = t.account_id
WHERE t.id = $1
  AND a.user_id = $2
  AND a.deleted_at IS NULL
  AND t.deleted_at IS NULL
`

type GetTransactionByIDForUserParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetTransactionByIDForUser(ctx context.Context, arg GetTransactionByIDForUserParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByIDForUser, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CategoryID,
		&i.RecurringID,
		&i.Amount,
		&i.Currency,
		&i.Type,
		&i.Description,
		&i.Notes,
		&i.TransactedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTransactionByIDForUserForUpdate = `-- name: GetTransactionByIDForUserForUpdate :one
SELECT t.id, t.account_id, t.category_id, t.recurring_id, t.amount, t.currency, t.type, t.description, t.notes, t.transacted_at, t.created_at, t.updated_at, t.deleted_at
FROM transactions t
JOIN accounts a ON a.id = t.account_id
WHERE t.id = $1
  AND a.user_id = $2
  AND a.deleted_at IS NULL
  AND t.deleted_at IS NULL
FOR UPDATE
`

type GetTransactionByIDForUserForUpdateParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetTransactionByIDForUserForUpdate(ctx context.Context, arg GetTransactionByIDForUserForUpdateParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByIDForUserForUpdate, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CategoryID,
		&i.RecurringID,
		&i.Amount,
		&i.Currency,
		&i.Type,
		&i.Description,
		&i.Notes,
		&i.TransactedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTransactionsForUser = `-- name: ListTransactionsForUser :many
SELECT t.id, t.account_id, t.category_id, t.recurring_id, t.amount, t.currency, t.type, t.description, t.notes, t.transacted_at, t.created_at, t.updated_at, t.deleted_at
FROM transactions t
JOIN accounts a ON a.id = t.account_id
WHERE a.user_id = $1
  AND a.deleted_at IS NULL
  AND t.deleted_at IS NULL
  AND ($2::bigint IS NULL OR t.account_id = $2::bigint)
  AND ($3::bigint IS NULL OR t.category_id = $3::bigint)
  AND ($4::text IS NULL OR t.type = $4::text)
  AND ($5::date IS NULL OR t.transacted_at >= $5::date)
  AND ($6::date IS NULL OR t.transacted_at <= $6::date)
ORDER BY t.transacted_at DESC, t.id DESC
LIMIT $8
OFFSET $7
`

type ListTransactionsForUserParams struct {
	UserID     int64
	AccountID  pgtype.Int8
	CategoryID pgtype.Int8
	Type       pgtype.Text
	FromDate   pgtype.Date
	ToDate     pgtype.Date
	OffsetRows int32
	LimitRows  int32
}

func (q *Queries) ListTransactionsForUser(ctx context.Context, arg ListTransactionsForUserParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsForUser,
		arg.UserID,
		arg.AccountID,
		arg.CategoryID,
		arg.Type,
		arg.FromDate,
		arg.ToDate,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.CategoryID,
			&i.RecurringID,
			&i.Amount,
			&i.Currency,
			&i.Type,
			&i.Description,
			&i.Notes,
			&i.TransactedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTransactionByIDForUser = `-- name: SoftDeleteTransactionByIDForUser :execrows
UPDATE transactions t
SET deleted_at = NOW(),
    updated_at = NOW()
FROM accounts a
WHERE t.id = $1
  AND a.id = t.account_id
  AND a.user_id = $2
  AND a.deleted_at IS NULL
  AND t.deleted_at IS NULL
`

type SoftDeleteTransactionByIDForUserParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) SoftDeleteTransactionByIDForUser(ctx context.Context, arg SoftDeleteTransactionByIDForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteTransactionByIDForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAccountBalanceDeltaByIDForUser = `-- name: UpdateAccountBalanceDeltaByIDForUser :one
UPDATE accounts
SET balance = balance + $3,
    updated_at = NOW()
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
RETURNING id, user_id, name, account_type, balance, currency, is_active, created_at, updated_at, deleted_at
`

type UpdateAccountBalanceDeltaByIDForUserParams struct {
	ID      int64
	UserID  int64
	Balance pgtype.Numeric
}

func (q *Queries) UpdateAccountBalanceDeltaByIDForUser(ctx context.Context, arg UpdateAccountBalanceDeltaByIDForUserParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountBalanceDeltaByIDForUser, arg.ID, arg.UserID, arg.Balance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AccountType,
		&i.Balance,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTransactionByIDForUser = `-- name: UpdateTransactionByIDForUser :one
UPDATE transactions t
SET amount = COALESCE($3, t.amount),
    category_id = COALESCE($4, t.category_id),
    notes = COALESCE($5, t.notes),
    updated_at = NOW()
FROM accounts a
WHERE t.id = $1
  AND a.id = t.account_id
  AND a.user_id = $2
  AND a.deleted_at IS NULL
  AND t.deleted_at IS NULL
RETURNING t.id, t.account_id, t.category_id, t.recurring_id, t.amount, t.currency, t.type, t.description, t.notes, t.transacted_at, t.created_at, t.updated_at, t.deleted_at
`

type UpdateTransactionByIDForUserParams struct {
	ID         int64
	UserID     int64
	Amount     pgtype.Numeric
	CategoryID pgtype.Int8
	Notes      pgtype.Text
}

func (q *Queries) UpdateTransactionByIDForUser(ctx context.Context, arg UpdateTransactionByIDForUserParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransactionByIDForUser,
		arg.ID,
		arg.UserID,
		arg.Amount,
		arg.CategoryID,
		arg.Notes,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CategoryID,
		&i.RecurringID,
		&i.Amount,
		&i.Currency,
		&i.Type,
		&i.Description,
		&i.Notes,
		&i.TransactedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
