// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: transactions.sql

package queries

import (
	"context"
)

const createTransaction = `-- name: CreateTransaction :one

INSERT INTO transactions (account_id, amount, description, transaction_type)
VALUES ($1, $2, $3, $4)
RETURNING id, account_id, amount, description, transaction_type, created_at
`

type CreateTransactionParams struct {
	AccountID       int32
	Amount          string
	Description     string
	TransactionType string
}

// Transactions
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.AccountID,
		arg.Amount,
		arg.Description,
		arg.TransactionType,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.Description,
		&i.TransactionType,
		&i.CreatedAt,
	)
	return i, err
}

const listTransactionsByAccountID = `-- name: ListTransactionsByAccountID :many
SELECT id, account_id, amount, description, transaction_type, created_at
FROM transactions
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByAccountIDParams struct {
	AccountID int32
	Limit     int32
	Offset    int32
}

func (q *Queries) ListTransactionsByAccountID(ctx context.Context, arg ListTransactionsByAccountIDParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByAccountID, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.Description,
			&i.TransactionType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
