// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name, currency)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, name, currency, role, is_active, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Name         string
	Currency     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Currency,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Currency,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, currency, role, is_active, created_at, updated_at, deleted_at
FROM users
WHERE email = $1
  AND deleted_at IS NULL
  AND is_active = TRUE
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Currency,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, currency, role, is_active, created_at, updated_at, deleted_at
FROM users
WHERE id = $1
  AND deleted_at IS NULL
  AND is_active = TRUE
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Currency,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, revoked, created_at
`

type InsertRefreshTokenParams struct {
	UserID    int64
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, insertRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const listValidRefreshTokens = `-- name: ListValidRefreshTokens :many
SELECT id, user_id, token_hash, expires_at, revoked, created_at
FROM refresh_tokens
WHERE revoked = FALSE
  AND expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) ListValidRefreshTokens(ctx context.Context) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, listValidRefreshTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefreshToken
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.Revoked,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValidRefreshTokensByUser = `-- name: ListValidRefreshTokensByUser :many
SELECT id, user_id, token_hash, expires_at, revoked, created_at
FROM refresh_tokens
WHERE user_id = $1
  AND revoked = FALSE
  AND expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) ListValidRefreshTokensByUser(ctx context.Context, userID int64) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, listValidRefreshTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefreshToken
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.Revoked,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRefreshTokenByID = `-- name: RevokeRefreshTokenByID :execrows
UPDATE refresh_tokens
SET revoked = TRUE
WHERE id = $1
  AND revoked = FALSE
`

func (q *Queries) RevokeRefreshTokenByID(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshTokenByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshTokenByIDForUser = `-- name: RevokeRefreshTokenByIDForUser :execrows
UPDATE refresh_tokens
SET revoked = TRUE
WHERE id = $1
  AND user_id = $2
  AND revoked = FALSE
`

type RevokeRefreshTokenByIDForUserParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) RevokeRefreshTokenByIDForUser(ctx context.Context, arg RevokeRefreshTokenByIDForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshTokenByIDForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password_hash = $2,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, email, password_hash, name, currency, role, is_active, created_at, updated_at, deleted_at
`

type UpdateUserPasswordParams struct {
	ID           int64
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Currency,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET name = COALESCE($2::text, name),
    currency = COALESCE($3::text, currency),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, email, password_hash, name, currency, role, is_active, created_at, updated_at, deleted_at
`

type UpdateUserProfileParams struct {
	ID       int64
	Name     pgtype.Text
	Currency pgtype.Text
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.Name, arg.Currency)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Currency,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $2,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
  AND is_active = TRUE
RETURNING id, email, password_hash, name, currency, role, is_active, created_at, updated_at, deleted_at
`

type UpdateUserRoleParams struct {
	ID   int64
	Role string
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Currency,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
